language: node_js

node_js:
  - 8

sudo: false

env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: ihRpp1gFZulqR5oLKVFlHb50tXAinK4tlXsciQZTSX9BceaSRaFiNo8qbX6ks9vmrmuuB4Fnp+BkfXYcRJw/UDv5vyR5aG5Sil311dGgzwwZKWpWVBuSPwmIEXYQgZkhu9unWWJlySWNp1jNeSAtDDhk5wCusSKC4NdMJhZGqwzKeT17hpBpq+Mi9rUw+5c/8yGdqjUiso7vHXELY8aoqDz5fJ3Ar3yXKNeyvsINLQy/5AwgjWQgcbJdBLWDRY0eLKuqaG7bJ6kCuOMmTyOic7fFxxCG5b6c39oFlEXfeLPCwXeHbcnJucdz2fRbGUqaRj9m5kZsVrTIfmZTBc4ndJcgkyvIiqlVEOTWgL5ui9PhjvscgRDn7Po/CRrf69z5xYCwJPfsu5/MDjcQVUjAyw7jxyy1A/IDqGYya+Tq1FKysGsVxhHTNgelqom1s1KmsjsTaKgsVvZ9n9lzYSzsnCbtqf3cX0eRb6iUVYsGHcKgH9oTou2Z0vRJ1FmlLbwoMx8jhFrTo6fmDIPA4gfseP43BPLy4UUPQnoZ2qJ/A5zTQ08UbXMbohWOIS8NBuCmsZlOyoU9Rkkze/65qlIEfkEssIlvQKR1kV+bLIhcsnuHz5qUZXsCPcslsc93ThzjM9kM9rXJzxiX7cNx6gtePTOxlH+4qU+eMcGbw7hmhqY=
    # COVERALLS_REPO_TOKEN
    - secure: M3L9K+zqUU+JgquJPQrCAlExiMv2BijFQzJy3/De1MXhiq6ZtuycLxCkat/Jsoo2TX3Oi9JfZmXi7idstEPdsfFFW61z467fnj3nm/l8wvSLPSWBDFryCXq25Oqli/Uc9NDSWCwZFz5CRKJOqo+fQ7lnPyc7l5by+ZlDaPJ7H8dNu2lk6KcSdJFD6gADFE9kns7AQFxaPchmhV56Q9UO07pLks2ij8fLZmjxUfN4lnwkwE9np2/34GHNRC2zROy3L0e5UzNsKZhpmkMW1ZclJ4yk0/BG+1M2AB90LWFPBZHLiZCrR6WLRlC5Fa14Puwk7fCV83DpUADaFmTO7B5dy/CSZPSPKAofocQ0PNz8PI+rPIGXfKapMpD4QnOFG85h2AhTBdTzAnrDoY2wgfVOFhGkGCCIFOyPU38EvaqdBybV8mcbxlTjFWoFOIRppbS+L06aurp1B6s+r67Gg2nmyUzrcS3FSIpUuqlSqQTxvwpXDmJwgcoL94xG1m4RRZIyIof0QKWKBhv0W1zJdvKvb6+i+2IgyTJNCpxtK3ePt3s6y4IQowwnYwvazetH2CHKTprMK07c/Q1EZY9bhcfodSR5J0bvLmPaoBMMcvNW+EjT93eWJ+1h/0TeIdWS89cs3yJk38kbeuKXvM1tUqwVRYaI71GJl3ZnKImrJhvX+lY=

cache:
  directories:
    - node_modules

before_script:
  - export KARMA_BROWSERS=Firefox,PhantomJS
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - ./node_modules/.bin/istanbul cover --report lcovonly ./node_modules/.bin/karma -- start ./test/karma.conf.js --single-run
  - cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls

deploy:
  - provider: npm
    email: rs@ruslansagitov.name
    api_key:
      secure: AUdj8mkjXQmouQJVIx/82pGX7GmHc01auLdb69uk9t5d1j523Ia4r38yOAu0suhOWB8p9XA48k2kGtBIr7FHJWPU3nLyalv8G3xHHp4S6FEzzIzJDPxFYXeppsUWDdJOD4eNwShFW+Cv6gfkGT8uLsD4Vu0wrRK6Bme7tfz6VMX3PfONlwNySpGW9+wbMSjNSJcHVvZI/V/tOREw4x4pbhryFIRkQRpbpZdSlDuL8OOZgTna/dPmA29JWcRjI0pVMzTCOikbqCFiH5tntcq4pNr1XCR8MH3XDwSAfR5fKgjx9tI0kn2YGz4LHKqO4VBjUPBZGrQf/P4A/XTG36oIPUh0WVFiVicYvI4V+UHojlStY0HCJoJ/7nHHaErCcDXAq77/Jtz48fnXjU+w3TfP+PdzLsr6K/TCSIyJqlzkdJBU4aMEhMDQapoG+tXNka/uuPj0ZYPwqSwCkvwbjjFKLIbtAVuOMlBWH80LRIigU16j2PislbKhNAu5jpMKpD5X/gsp5wkHuUQma84kVqdj4HznjqGrvMSAR1NfcXu9FpUNuXVgXrGoscu9C68m9k0pYig7AxL/tHzvfpPlwtrACCpwtpsjHJIisUSa7aWr20FKXlbnhDHjNAYTPYjRIB1XjhtOAJxTzroWQyVDwc9h35oXprW1krYWCku9VZxpDfg=
    on:
      all_branches: true
      tags: true
      repo: ruslansagitov/karma-jasmine-loud
